### ISSUE TITLE
Data not Updated 04.01.2021

### ISSUE THREAD

**Issue by ghost** [thohan88/covid19-nor-data#10]
Hi, 

Thank you for great work on making this data available!

The last couple of days, the data has not been updated. Will this be fixed in the near future?

Best Regards
Are

**Comment by ghost** [comment]
It now seems to be working. Thanks:)

**Comment by thohan88** [comment]
Thanks for reporting this, @AreHH. It made me aware that we haven't scraped 2021-figures correctly so far. The daily changes from 1st to 4th of January is currently only due to delayed reporting. Sorry for the inconvenience - hope to fix this during the weekend!

**Comment by ghost** [comment]
Thank you, It's much appreciated!

**Comment by ghost** [comment]
Hi,

did you manage to fix this during the weekend?

**Comment by ghost** [comment]
> Thanks for reporting this, @AreHH. It made me aware that we haven't scraped 2021-figures correctly so far. The daily changes from 1st to 4th of January is currently only due to delayed reporting. Sorry for the inconvenience - hope to fix this during the weekend!

Hi,

do you have any update on this? I don't mean to push, I just need to provide a status to my clients about when this could be up and running again:)

**Comment by thohan88** [comment]
Hi again,
Yeah, this was fixed on the 5th of January. It did have some consequence for the period between the 1st and 4th of January. More specifically, reported cases for these days only include lagged registrations which actually occurred in the last days of 2020. From the 5th and onwards, "new" 2021-cases are included in the numbers, so it will potentially give a small spike for the 5th. 

![image](https://user-images.githubusercontent.com/16469189/105244444-db618c00-5b70-11eb-861d-2ff07e2415ee.png)
