### ISSUE TITLE
Missing data...

### ISSUE THREAD

**Issue by NRVA** [thohan88/covid19-nor-data#11]
ICYMI: The dataset seems to stop at February 11th 2021!?

Btw, thank you so much for making this data accessible. I have used it a lot, both in my [web application](https://c19-nord.herokuapp.com) and in my [automated newsletter](https://helse-nord.us2.list-manage.com/subscribe?u=5a019e31b7bacd304458ab393&id=77d0c775d0). 

Great work

**Comment by aholmis** [comment]
The github action is failing.

Error in py_run_file_impl(file, local, convert) : 
  AttributeError: 'NoneType' object has no attribute 'group'

Detailed traceback: 
  File "<string>", line 13, in <module>
Calls: source ... withVisible -> eval -> eval -> <Anonymous> -> py_run_file_impl
Execution halted
Error: Process completed with exit code 1.

**Comment by thohan88** [comment]
Thanks for the heads-up. Seems like FHI have changed their structure for death statistics. I currently don't have the time to fix the formatting, but failing python-jobs are now skipped so that other sources are still being updated.
