### ISSUE TITLE
Admission / Hospitalised

### ISSUE THREAD

**Issue by philipus** [thohan88/covid19-nor-data#5]
What means admission?

people who entered at the date the hospital or the number of people being in the hospital (hospitalised)?

**Comment by thohan88** [comment]
Thanks, this needed a clarification. It is the number of people in hospital (inpatient stay) at the given date. I have added this to the description in the data-section.

**Comment by thohan88** [comment]
Updated description in 4de786922f97287e71c7d7ad391b9abc304987eb
