### ISSUE TITLE
Data is not updating

### ISSUE THREAD

**Issue by HoppyJoe** [thohan88/covid19-nor-data#6]
No data is updating on this service. Has not been updated since May 19. Possible to fix this issue?

**Comment by thohan88** [comment]
Thanks for the heads-up. I have been meaning to rewrite the updating script for a while. It should now be more robust, and will not stop if it is unable to update one of the data sources. You should see daily updates coming in from now.

Unfortunately, all data sources are not available through API's so there will always be some risk of changes to format and structure. Feel free to re-open this issue if you are seeing any issues.
